### ISSUE TITLE
3D print the parts

### ISSUE THREAD

**Issue by Serban2003** [RIVER-Project/ExoMyRover#6]

**Comment by NEjjjO** [comment]
Nu prea am cand sa-l printez si nici nu am mult filament. Doar ce a ramas din primul ExoMy. Poti sa printezi si tu niste piese si sa comandam filament? @Serban2003

**Comment by Serban2003** [comment]
> Nu prea am cand sa-l printez si nici nu am mult filament. Doar ce a ramas din primul ExoMy. Poti sa printezi si tu niste piese si sa comandam filament? [@Serban2003](https://github.com/Serban2003)

Da, o sa dau comanda de filament si abia de saptaman viitoare o sa ne apucam de printat.  @NEjjjO
